In [1]:
import numpy as np

In [2]:
a = np.array([3,4,5,6,2,567,3,57,3,6])

In [3]:
a.shape

(10,)

In [4]:
b = np.array([[34,56,345,7,3,5],[45,5,47,4,832,6]])
b

array([[ 34,  56, 345,   7,   3,   5],
       [ 45,   5,  47,   4, 832,   6]])

In [5]:
b.shape

(2, 6)

In [6]:
a.reshape(2,5)

array([[  3,   4,   5,   6,   2],
       [567,   3,  57,   3,   6]])

In [7]:
a.reshape(5,2)

array([[  3,   4],
       [  5,   6],
       [  2, 567],
       [  3,  57],
       [  3,   6]])

In [9]:
b.T

array([[ 34,  45],
       [ 56,   5],
       [345,  47],
       [  7,   4],
       [  3, 832],
       [  5,   6]])

In [10]:
b.dtype

dtype('int32')

In [12]:
np.random.rand(3,4)

array([[0.12465783, 0.5374218 , 0.54426618, 0.91622511],
       [0.04613927, 0.32590194, 0.12961404, 0.25689347],
       [0.0243514 , 0.8281413 , 0.9587031 , 0.60160561]])

In [13]:
np.random.randint(1,1000, (4,5))

array([[231, 776,  67, 747, 169],
       [169, 226, 880, 710,  91],
       [783, 312, 225, 446, 980],
       [280, 344, 808, 398, 566]])

In [14]:
import random

In [15]:
np.random.randn(3,4)

array([[ 0.1962981 ,  1.25050712, -0.87132003, -0.09390664],
       [ 0.50239217,  0.11214753, -0.19106411, -1.19713595],
       [-1.51339421,  0.49392806,  0.7561912 , -0.19846767]])

In [16]:
a.resize(2,5)

In [17]:
a

array([[  3,   4,   5,   6,   2],
       [567,   3,  57,   3,   6]])

In [18]:
a.resize(2,5,1)

In [19]:
a

array([[[  3],
        [  4],
        [  5],
        [  6],
        [  2]],

       [[567],
        [  3],
        [ 57],
        [  3],
        [  6]]])

In [20]:
a.resize(1,2,5)

In [21]:
a

array([[[  3,   4,   5,   6,   2],
        [567,   3,  57,   3,   6]]])

In [29]:
a.resize(2,5)

In [30]:
a

array([[  3,   4,   5,   6,   2],
       [567,   3,  57,   3,   6]])

In [31]:
a.sum()

656

In [33]:
a.sum(axis=0) # gives sum in row or sum of each column

array([570,   7,  62,   9,   8])

In [35]:
a.sum(axis=1) # sum in column or sum of each row

array([ 20, 636])

In [23]:
a.mean()

65.6

In [36]:
a.mean(axis=0)

array([285. ,   3.5,  31. ,   4.5,   4. ])

In [24]:
a.var()

28184.839999999997

In [25]:
a.max()

567

In [26]:
a.argmax()

5

In [28]:
a.min()

2

In [37]:
a * 2

array([[   6,    8,   10,   12,    4],
       [1134,    6,  114,    6,   12]])

In [38]:
a + 2

array([[  5,   6,   7,   8,   4],
       [569,   5,  59,   5,   8]])

In [46]:
a.shape

(2, 5)

In [45]:
np.array([[70],[80]]).shape

(2, 1)

In [49]:
np.append(a,[[70],[80]],axis=1)

array([[  3,   4,   5,   6,   2,  70],
       [567,   3,  57,   3,   6,  80]])

In [54]:
k = np.append(a, [[4,5,6,83,9]],axis=0)
k

array([[  3,   4,   5,   6,   2],
       [567,   3,  57,   3,   6],
       [  4,   5,   6,  83,   9]])

In [56]:
np.save('myfile.npy',k)

In [57]:
m = np.load('myfile.npy')

In [58]:
m

array([[  3,   4,   5,   6,   2],
       [567,   3,  57,   3,   6],
       [  4,   5,   6,  83,   9]])

In [59]:
np.save('other.npy',{'a':45})

In [61]:
d = np.load('other.npy',allow_pickle=True)

In [67]:
d = d.tolist()

In [68]:
d

{'a': 45}

In [69]:
type(d)

dict

In [73]:
np.savetxt('afile.csv',a,fmt='%d',delimiter=',',header='a,b,c,d,e')

In [76]:
c = np.loadtxt('afile.csv',dtype=int,delimiter=',',)
c

array([[  3,   4,   5,   6,   2],
       [567,   3,  57,   3,   6]])

## Pandas

1. Series - 1D Data/Single Column
2. DataFrame - 2D Data/MultiColumn/Tabular
3. Panel - 3D Data/MultiTable

In [77]:
import pandas as pd

In [80]:
import warnings
warnings.filterwarnings('ignore')

In [81]:
s = pd.Series()

In [82]:
s

Series([], dtype: float64)

In [83]:
s.shape

(0,)

In [84]:
s.size

0

In [85]:
len(s)

0

In [86]:
s.dtype

dtype('float64')

In [87]:
s1 = pd.Series([4,5,7,4,87,43,8,3])
s1

0     4
1     5
2     7
3     4
4    87
5    43
6     8
7     3
dtype: int64

In [88]:
s1[5]

43

In [89]:
s1.head(3)

0    4
1    5
2    7
dtype: int64

In [90]:
s1.tail(4)

4    87
5    43
6     8
7     3
dtype: int64

In [91]:
s1.head()

0     4
1     5
2     7
3     4
4    87
dtype: int64

In [92]:
s1.sample(3)

1    5
6    8
0    4
dtype: int64

In [93]:
s1

0     4
1     5
2     7
3     4
4    87
5    43
6     8
7     3
dtype: int64

In [94]:
s1.sum()

161

In [95]:
s1.argmax()

4

In [96]:
s1.idxmax()

4

In [97]:
s1.var()

908.125

In [98]:
s1.std()

30.135112410608325

In [103]:
s1.value_counts()

4     2
3     1
5     1
87    1
8     1
43    1
7     1
dtype: int64

In [102]:
s1.value_counts()[87]

1

In [104]:
s1

0     4
1     5
2     7
3     4
4    87
5    43
6     8
7     3
dtype: int64

In [105]:
len(s1)

8

In [106]:
s1.values

array([ 4,  5,  7,  4, 87, 43,  8,  3], dtype=int64)

In [107]:
s1.nunique()

7

In [108]:
s1.count()

8

In [109]:
s1.unique()

array([ 4,  5,  7, 87, 43,  8,  3], dtype=int64)

In [110]:
# logical Indexing

In [114]:
type(s1)

pandas.core.series.Series

In [112]:
type(s1.value_counts())

pandas.core.series.Series

In [125]:
sum(s1.value_counts()==1)

6

In [123]:
list(s1.value_counts()[s1.value_counts()==1].index)

[3, 5, 87, 8, 43, 7]

In [119]:
s1[s1>10]

4    87
5    43
dtype: int64

In [120]:
s1.index

RangeIndex(start=0, stop=8, step=1)

In [121]:
s1

0     4
1     5
2     7
3     4
4    87
5    43
6     8
7     3
dtype: int64

In [126]:
df1 = pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [127]:
df2 = pd.DataFrame([4,5,7,983,765])
df2

0
0    4
1    5
2    7
3  983
4  765

In [128]:
b

array([[ 34,  56, 345,   7,   3,   5],
       [ 45,   5,  47,   4, 832,   6]])

In [129]:
b.T

array([[ 34,  45],
       [ 56,   5],
       [345,  47],
       [  7,   4],
       [  3, 832],
       [  5,   6]])

In [130]:
df3 = pd.DataFrame(b.T)
df3

0    1
0   34   45
1   56    5
2  345   47
3    7    4
4    3  832
5    5    6

In [132]:
df3[1]

0     45
1      5
2     47
3      4
4    832
5      6
Name: 1, dtype: int32

In [134]:
df3.loc[2]

0    345
1     47
Name: 2, dtype: int32

In [136]:
df3.head(2)

0   1
0  34  45
1  56   5

In [137]:
df3.sample(2)

0   1
0  34  45
3   7   4

In [138]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6 non-null      int32
 1   1       6 non-null      int32
dtypes: int32(2)
memory usage: 176.0 bytes


In [140]:
df3.isnull().sum()

0    0
1    0
dtype: int64

In [141]:
df3.describe()

0           1
count    6.00000    6.000000
mean    75.00000  156.500000
std    133.90295  331.536273
min      3.00000    4.000000
25%      5.50000    5.250000
50%     20.50000   25.500000
75%     50.50000   46.500000
max    345.00000  832.000000

In [143]:
df3

0    1
0   34   45
1   56    5
2  345   47
3    7    4
4    3  832
5    5    6

In [144]:
a

array([[  3,   4,   5,   6,   2],
       [567,   3,  57,   3,   6]])

In [147]:
df4 = pd.DataFrame(a.T)

In [148]:
df4

0    1
0  3  567
1  4    3
2  5   57
3  6    3
4  2    6

In [149]:
df4.value_counts()

0  1  
2  6      1
3  567    1
4  3      1
5  57     1
6  3      1
dtype: int64

In [152]:
s1.describe()

count     8.000000
mean     20.125000
std      30.135112
min       3.000000
25%       4.000000
50%       6.000000
75%      16.750000
max      87.000000
dtype: float64

In [153]:
df4

0    1
0  3  567
1  4    3
2  5   57
3  6    3
4  2    6

In [156]:
df4.sum(axis=1)

0    570
1      7
2     62
3      9
4      8
dtype: int64

In [158]:
df44 = df4.sort_values(1)
df44

0    1
1  4    3
3  6    3
4  2    6
2  5   57
0  3  567

In [159]:
df44.sort_index()

0    1
0  3  567
1  4    3
2  5   57
3  6    3
4  2    6